"""Added default values for Employee

Revision ID: 585b78bd3a6c
Revises: cf4d9e57b7e5
Create Date: 2021-04-12 17:31:40.822625

"""
from alembic import op
import sqlalchemy as sa

from datetime import datetime


# revision identifiers, used by Alembic.
revision = '585b78bd3a6c'
down_revision = 'cf4d9e57b7e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'state', server_default=str(None))
    op.alter_column('employees', 'city', server_default=str(None))
    op.alter_column('employees', 'address', server_default=str(None))
    op.alter_column('employees', 'postcode', server_default=str(None))

    op.alter_column('employees', 'birthday', server_default=str(datetime.utcnow()))
    op.alter_column('employees', 'start_date', server_default=str(datetime.utcnow()))
    op.alter_column('employees', 'end_date', server_default=str(datetime.utcnow()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'state', server_default=None)
    op.alter_column('employees', 'city', server_default=None)
    op.alter_column('employees', 'address', server_default=None)
    op.alter_column('employees', 'postcode', server_default=None)

    op.alter_column('employees', 'birthday', server_default=None)
    op.alter_column('employees', 'start_date', server_default=None)
    op.alter_column('employees', 'end_date', server_default=None)


    # ### end Alembic commands ###
