"""Alter table add default val/null

Revision ID: b22041c293c5
Revises: 952bbcd2f9e0
Create Date: 2021-03-26 14:51:20.656707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22041c293c5'
down_revision = '952bbcd2f9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'patronymic',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.alter_column('employees', 'corp_email',
                    server_default="example@gmail.com")
    op.alter_column('employees', 'personal_email',
                    server_default="example@gmail.com")
    op.alter_column('employees', 'phone_number',
                    server_default="+380000000000")
    op.alter_column('employees', 'country',
                    server_default="Ukraine")
    op.alter_column('employees', 'is_active',
                    server_default="true")
    op.alter_column('employees', 'is_approved',
                    server_default="true")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'patronymic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.alter_column('employees', 'corp_email',
                    server_default="NULL")
    op.alter_column('employees', 'personal_email',
                    server_default="NULL")
    op.alter_column('employees', 'phone_number',
                    server_default="NULL")
    op.alter_column('employees', 'country',
                    server_default="NULL")
    op.alter_column('employees', 'is_active',
                    server_default="NULL")
    op.alter_column('employees', 'is_approved',
                    server_default="NULL")
    # ### end Alembic commands ###
