"""removed null constraint

Revision ID: b4480120c00c
Revises: b22041c293c5
Create Date: 2021-03-26 15:46:17.155658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4480120c00c'
down_revision = 'b22041c293c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'patronymic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'patronymic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
